# Update all versions in this file by running:
#   $ pre-commit autoupdate
minimum_pre_commit_version: 2.19.0
default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
        name: Check for a blank line at the end of scripts (auto-fixes)
        exclude: ^solutions/
      - id: trailing-whitespace
      - id: check-builtin-literals
        exclude: |
            (?x)^(
                solutions/02_21.py|
                solutions/04_05.py|
                solutions/05_01.py|
                solutions/05_12.py
            )$
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: debug-statements
        exclude: |
              (?x)^(
                  solutions/02_21.py|
                  solutions/04_05.py|
                  solutions/05_01.py|
                  solutions/05_12.py
              )$
      - id: detect-private-key
      - id: mixed-line-ending
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: check-yaml
      - id: check-added-large-files
        name: Check for files larger than 5 MB
        args: ["--maxkb=5120"]
      - id: check-ast
        exclude: |
                (?x)^(
                    solutions/02_21.py|
                    solutions/04_05.py|
                    solutions/05_01.py|
                    solutions/05_12.py
                )$
      - id: check-docstring-first
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: &autoflake
          - --in-place
          - --remove-all-unused-imports
          - --expand-star-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
        exclude: |
              (?x)^(
                  solutions/02_01.py
              )$
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - &flake8
        id: flake8
        additional_dependencies:
          - flake8-docstrings==1.6.0
          - flake8-eradicate==1.2.0
          - flake8-fixme==1.1.1
          - flake8-implicit-str-concat==0.2.0
          - flake8-print==4.0.0
          - flake8-return==1.1.3
        args: ["--config=setup.cfg"]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.3
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        types: [python]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
        args:
          - "--py310-plus"
  - repo: https://github.com/Cielquan/mirrors-poetry
    rev: 1.1.13
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update"]
      - id: poetry-export
        args: ["--without-hashes"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        types_or: [yaml]
        additional_dependencies:
          - "prettier@2.5.1"
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint tests
        language: system
        always_run: true
        pass_filenames: false
        stages: [manual]
      - id: pip-audit
        name: pip-audit
        entry: pip-audit
        language: system
        always_run: true
        pass_filenames: false
        stages: [manual]
